# Generated by Django 4.2.5 on 2023-09-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dateEmbauche', models.DateField(blank=True, null=True)),
                ('timeConsultation', models.TimeField()),
                ('posteDescription', models.TextField()),
                ('experience', models.PositiveIntegerField()),
                ('contrat', models.BooleanField(default=False)),
                ('linked', models.URLField()),
                ('slug', models.SlugField()),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
