# Generated by Django 4.2.5 on 2023-10-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zugus', '0002_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='compte',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
