# Generated by Django 4.2.5 on 2023-10-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zugus', '0004_device_alter_compte_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
